version: "3"

services:
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node # only one instance is enough for dev
      - cluster.name=vahy # same cluster name as production
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false # disable auth on localhost
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./.data/es-local:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    volumes:
      - ./.docker/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - search
    links:
      - search:elasticsearch